export type AppPalette = {
  surface: string;
  background: string;
  elevated: string;
  elevatedAlt: string;
  elevatedDark: string;
  border: string;
  borderAlt: string;
  text: string;
  textMuted: string;
  textSoft: string;
  accent: string;
  accentSoft: string;
  accentText: string;
  accentContrastText: string;
  inverseText: string;
  inverseMuted: string;
  tag: string;
  tagText: string;
  searchPlaceholder: string;
  headerBackground: string;
  highlightTemp: string;
  highlightTempText: string;
  highlightDoneness: string;
  highlightDonenessText: string;
  highlightMethod: string;
  highlightMethodText: string;
  highlightEquipment: string;
  highlightEquipmentText: string;
  warningBg: string;
  warningBorder: string;
  warningText: string;
  addButtonBg: string;
  addButtonBorder: string;
  addButtonText: string;
};

export const lightPalette: AppPalette = {
  surface: '#fff7ea',
  background: '#f4efe6',
  elevated: '#fffdf9',
  elevatedAlt: '#fdf3df',
  elevatedDark: '#7a2f1d',
  border: '#e8dccb',
  borderAlt: '#ead2ab',
  text: '#2a2118',
  textMuted: '#5c4d3c',
  textSoft: '#8f775b',
  accent: '#7a2f1d',
  accentSoft: '#e4b66b',
  accentText: '#8a5a24',
  accentContrastText: '#fff6eb',
  inverseText: '#fff6eb',
  inverseMuted: '#f2d7c3',
  tag: '#f4dfba',
  tagText: '#6f4817',
  searchPlaceholder: '#8f775b',
  headerBackground: '#fff7ea',
  highlightTemp: '#f9d6c4',
  highlightTempText: '#7a2f1d',
  highlightDoneness: '#dce9c9',
  highlightDonenessText: '#33511c',
  highlightMethod: '#e7ddf2',
  highlightMethodText: '#4a2d63',
  highlightEquipment: '#dfe7ef',
  highlightEquipmentText: '#2f4a63',
  warningBg: '#fff1e8',
  warningBorder: '#e8b08a',
  warningText: '#9b4c20',
  addButtonBg: '#fff8ef',
  addButtonBorder: '#edca88',
  addButtonText: '#4a2d63',
};

export const darkPalette: AppPalette = {
  surface: '#1d1712',
  background: '#120f0c',
  elevated: '#231c16',
  elevatedAlt: '#2a2119',
  elevatedDark: '#3a281e',
  border: '#4a3b2f',
  borderAlt: '#5c4736',
  text: '#f5eadf',
  textMuted: '#d7c1ac',
  textSoft: '#b89b81',
  accent: '#f0b35f',
  accentSoft: '#f0b35f',
  accentText: '#f0b35f',
  accentContrastText: '#1d1712',
  inverseText: '#fff6eb',
  inverseMuted: '#e3cdb6',
  tag: '#3a2d22',
  tagText: '#f5d8aa',
  searchPlaceholder: '#a88d74',
  headerBackground: '#1d1712',
  highlightTemp: '#4a2520',
  highlightTempText: '#f9c4ad',
  highlightDoneness: '#2a3a1f',
  highlightDonenessText: '#b8d49a',
  highlightMethod: '#2f2740',
  highlightMethodText: '#c4aadf',
  highlightEquipment: '#27323f',
  highlightEquipmentText: '#aac4df',
  warningBg: '#3e2a1c',
  warningBorder: '#6e472c',
  warningText: '#f3b98f',
  addButtonBg: '#2d2318',
  addButtonBorder: '#5c4736',
  addButtonText: '#c4aadf',
};
