import { StyleSheet } from 'react-native';

export const kitchenStyles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#f4efe6',
  },
  page: {
    paddingHorizontal: 20,
    paddingTop: 20,
    paddingBottom: 32,
    gap: 20,
  },
  hero: {
    backgroundColor: '#fff7ea',
    borderRadius: 28,
    padding: 24,
    borderWidth: 1,
    borderColor: '#eadac0',
    gap: 20,
  },
  heroWide: {
    flexDirection: 'row',
    alignItems: 'stretch',
  },
  heroCopy: {
    flex: 1.1,
    gap: 12,
  },
  eyebrow: {
    fontSize: 12,
    letterSpacing: 1.5,
    textTransform: 'uppercase',
    color: '#8a5a24',
    fontWeight: '700',
  },
  title: {
    fontSize: 36,
    lineHeight: 40,
    color: '#2a2118',
    fontWeight: '800',
  },
  subtitle: {
    fontSize: 16,
    lineHeight: 24,
    color: '#5c4d3c',
    maxWidth: 620,
  },
  badgeRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    marginTop: 4,
  },
  badge: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    backgroundColor: '#f5d8aa',
    color: '#6f4817',
    borderRadius: 999,
    fontWeight: '700',
  },
  heroCard: {
    flex: 0.9,
    backgroundColor: '#2a2118',
    borderRadius: 24,
    padding: 20,
    gap: 12,
  },
  heroCardLabel: {
    color: '#e4b66b',
    fontSize: 12,
    letterSpacing: 1.2,
    textTransform: 'uppercase',
    fontWeight: '700',
  },
  heroCardTitle: {
    color: '#fff6eb',
    fontSize: 24,
    fontWeight: '800',
  },
  heroCardText: {
    color: '#dbc8b6',
    fontSize: 15,
    lineHeight: 22,
  },
  contentGrid: {
    gap: 20,
  },
  contentGridWide: {
    flexDirection: 'row',
    alignItems: 'flex-start',
  },
  primaryColumn: {
    flex: 1.35,
    gap: 20,
  },
  secondaryColumn: {
    flex: 0.95,
    gap: 20,
  },
  panel: {
    backgroundColor: '#fffdf9',
    borderRadius: 24,
    padding: 20,
    borderWidth: 1,
    borderColor: '#e8dccb',
    gap: 12,
  },
  panelAlt: {
    backgroundColor: '#fdf3df',
    borderRadius: 24,
    padding: 20,
    borderWidth: 1,
    borderColor: '#ead2ab',
    gap: 12,
  },
  panelDark: {
    backgroundColor: '#7a2f1d',
    borderRadius: 24,
    padding: 20,
    gap: 12,
  },
  panelEyebrow: {
    fontSize: 12,
    letterSpacing: 1.3,
    textTransform: 'uppercase',
    color: '#9b6a2f',
    fontWeight: '700',
  },
  panelTitle: {
    fontSize: 24,
    lineHeight: 28,
    color: '#2b2017',
    fontWeight: '800',
  },
  panelText: {
    fontSize: 15,
    lineHeight: 22,
    color: '#5d4c3a',
  },
  servingsRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    marginTop: 6,
  },
  servingsButton: {
    borderRadius: 999,
    borderWidth: 1,
    borderColor: '#5b4734',
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  servingsButtonActive: {
    backgroundColor: '#e4b66b',
    borderColor: '#e4b66b',
  },
  servingsButtonText: {
    color: '#f8ecdd',
    fontWeight: '700',
  },
  servingsButtonTextActive: {
    color: '#2a2118',
  },
  ingredientList: {
    gap: 12,
    marginTop: 4,
  },
  ingredientRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 12,
    backgroundColor: '#f7efe3',
    borderRadius: 18,
    paddingHorizontal: 16,
    paddingVertical: 14,
  },
  ingredientAmount: {
    fontSize: 16,
    fontWeight: '800',
    color: '#2e241b',
  },
  ingredientName: {
    marginTop: 2,
    fontSize: 14,
    color: '#5f4f3c',
  },
  ingredientNote: {
    flexShrink: 1,
    textAlign: 'right',
    color: '#8f775b',
    fontSize: 13,
  },
  cardStack: {
    gap: 12,
    marginTop: 4,
  },
  menuGrid: {
    gap: 12,
    marginTop: 4,
  },
  menuCard: {
    borderRadius: 20,
    padding: 18,
    backgroundColor: '#fff7ea',
    borderWidth: 1,
    borderColor: '#edd8b1',
    gap: 8,
  },
  menuCardEyebrow: {
    fontSize: 12,
    color: '#8a5a24',
    textTransform: 'uppercase',
    letterSpacing: 1.1,
    fontWeight: '700',
  },
  menuCardTitle: {
    fontSize: 20,
    lineHeight: 24,
    color: '#2c2219',
    fontWeight: '800',
  },
  menuCardBody: {
    fontSize: 14,
    lineHeight: 21,
    color: '#5b4c3b',
  },
  menuCardLink: {
    fontSize: 14,
    color: '#7a2f1d',
    fontWeight: '800',
  },
  infoCard: {
    borderRadius: 18,
    padding: 16,
    backgroundColor: '#fff7ea',
    borderWidth: 1,
    borderColor: '#edd8b1',
    gap: 6,
  },
  infoCardTitle: {
    fontSize: 14,
    color: '#8a5a24',
    fontWeight: '700',
    textTransform: 'uppercase',
  },
  infoCardSwap: {
    fontSize: 18,
    color: '#2c2219',
    fontWeight: '800',
  },
  infoCardMeta: {
    fontSize: 33,
    color: '#845726',
    fontWeight: '700',
  },
  infoCardBody: {
    fontSize: 14,
    lineHeight: 21,
    color: '#5b4c3b',
  },
  conversionList: {
    gap: 12,
  },
  conversionRow: {
    backgroundColor: '#fff9ef',
    borderRadius: 18,
    padding: 16,
    gap: 4,
  },
  conversionFrom: {
    color: '#36281d',
    fontSize: 16,
    fontWeight: '800',
  },
  conversionArrow: {
    color: '#8f5f24',
    fontSize: 13,
    textTransform: 'uppercase',
    letterSpacing: 1,
    fontWeight: '700',
  },
  conversionResult: {
    color: '#7a2f1d',
    fontSize: 20,
    fontWeight: '800',
  },
  conversionTable: {
    width: '100%',
    gap: 2,
  },
  conversionTableRow: {
    flexDirection: 'row',
    alignItems: 'center',
    borderRadius: 10,
  },
  conversionTableHeader: {
    backgroundColor: '#f4dfba',
  },
  conversionTableCell: {
    flex: 1,
    paddingHorizontal: 6,
    paddingVertical: 8,
    color: '#5b4c3b',
    fontSize: 13,
    lineHeight: 17,
    textAlign: 'center',
  },
  conversionTableHeaderCell: {
    color: '#8a5a24',
    fontSize: 12,
    fontWeight: '800',
    letterSpacing: 0.8,
    textTransform: 'uppercase',
  },
  conversionTableAmountCell: {
    flex: 1.35,
    color: '#2c2219',
    fontWeight: '800',
    textAlign: 'left',
  },
  panelDarkEyebrow: {
    fontSize: 12,
    letterSpacing: 1.3,
    textTransform: 'uppercase',
    color: '#f3be7c',
    fontWeight: '700',
  },
  panelDarkTitle: {
    fontSize: 24,
    lineHeight: 28,
    color: '#fff6eb',
    fontWeight: '800',
  },
  panelDarkText: {
    color: '#f2d7c3',
    fontSize: 15,
    lineHeight: 22,
  },
  nextStep: {
    fontSize: 16,
    lineHeight: 22,
    color: '#3e2e21',
    fontWeight: '700',
    backgroundColor: '#fff9ef',
    borderRadius: 16,
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  listStack: {
    gap: 14,
    marginTop: 4,
  },
  detailCard: {
    borderRadius: 18,
    padding: 16,
    backgroundColor: '#fff9ef',
    borderWidth: 1,
    borderColor: '#ead2ab',
    gap: 6,
  },
  detailCardTitle: {
    fontSize: 18,
    lineHeight: 22,
    color: '#2c2219',
    fontWeight: '800',
  },
  detailCardHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 12,
  },
  detailCardMeta: {
    fontSize: 13,
    color: '#8a5a24',
    fontWeight: '700',
    textTransform: 'uppercase',
  },
  detailCardBody: {
    fontSize: 14,
    lineHeight: 21,
    color: '#5b4c3b',
  },
  tagRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginTop: 2,
  },
  tag: {
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
    backgroundColor: '#f4dfba',
  },
  tagText: {
    fontSize: 12,
    color: '#6f4817',
    fontWeight: '700',
  },
  allergenTag: {
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
    backgroundColor: '#e98d34',
  },
  allergenTagText: {
    fontSize: 12,
    color: '#fff7ea',
    fontWeight: '700',
  },
  allergyFriendlyTag: {
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
    backgroundColor: '#cfe9b5',
  },
  allergyFriendlyTagText: {
    fontSize: 12,
    color: '#33511c',
    fontWeight: '700',
  },
  cuisineTag: {
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
    backgroundColor: '#cfe7f7',
  },
  cuisineTagText: {
    fontSize: 12,
    color: '#1f4f73',
    fontWeight: '700',
  },
  numberGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginTop: 6,
  },
  numberButton: {
    minWidth: 44,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#5b4734',
    paddingHorizontal: 12,
    paddingVertical: 10,
    backgroundColor: '#fff7ea',
  },
  numberButtonActive: {
    backgroundColor: '#e4b66b',
    borderColor: '#e4b66b',
  },
  numberButtonDisabled: {
    opacity: 0.45,
  },
  numberButtonText: {
    color: '#2a2118',
    fontWeight: '800',
    fontSize: 14,
  },
  starButton: {
    minWidth: 38,
    minHeight: 38,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 999,
    backgroundColor: '#fff2d6',
    borderWidth: 1,
    borderColor: '#e8c992',
  },
  starButtonActive: {
    backgroundColor: '#f0c45b',
    borderColor: '#f0c45b',
  },
  starButtonText: {
    fontSize: 18,
    color: '#8a5a24',
    fontWeight: '800',
  },
  searchInput: {
    borderWidth: 1,
    borderColor: '#d8c3a2',
    backgroundColor: '#fff9ef',
    borderRadius: 16,
    paddingHorizontal: 14,
    paddingVertical: 12,
    fontSize: 15,
    color: '#2c2219',
    marginTop: 6,
  },
  formStack: {
    gap: 16,
    marginTop: 6,
  },
  formField: {
    gap: 8,
  },
  formLabel: {
    fontSize: 13,
    letterSpacing: 1.1,
    textTransform: 'uppercase',
    fontWeight: '700',
    color: '#8a5a24',
  },
  formHint: {
    fontSize: 13,
    lineHeight: 19,
    color: '#7a6650',
  },
  formInput: {
    borderWidth: 1,
    borderColor: '#d8c3a2',
    backgroundColor: '#fff9ef',
    borderRadius: 18,
    paddingHorizontal: 14,
    paddingVertical: 12,
    fontSize: 15,
    color: '#2c2219',
  },
  formTextArea: {
    minHeight: 140,
    textAlignVertical: 'top',
  },
  formTextAreaCompact: {
    minHeight: 110,
  },
  helperCard: {
    borderRadius: 18,
    padding: 16,
    borderWidth: 1,
    gap: 8,
  },
  helperCardTitle: {
    fontSize: 16,
    lineHeight: 20,
    fontWeight: '800',
  },
  helperCardBody: {
    fontSize: 14,
    lineHeight: 21,
  },
  noticeCard: {
    borderRadius: 20,
    padding: 16,
    borderWidth: 1,
    gap: 10,
  },
  noticeCardTitle: {
    fontSize: 16,
    lineHeight: 20,
    fontWeight: '800',
  },
  noticeCardBody: {
    fontSize: 14,
    lineHeight: 21,
  },
  noticeTimerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  noticeTimerGlyph: {
    width: 20,
    height: 20,
    alignItems: 'center',
    justifyContent: 'center',
  },
  noticeTimerText: {
    fontSize: 13,
    fontWeight: '700',
  },
  actionRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
    marginTop: 4,
  },
  primaryButton: {
    backgroundColor: '#7a2f1d',
    borderRadius: 999,
    paddingHorizontal: 18,
    paddingVertical: 12,
  },
  primaryButtonText: {
    color: '#fff7ea',
    fontWeight: '800',
    fontSize: 15,
  },
  secondaryButton: {
    backgroundColor: '#fff9ef',
    borderWidth: 1,
    borderColor: '#ead2ab',
    borderRadius: 999,
    paddingHorizontal: 18,
    paddingVertical: 12,
  },
  secondaryButtonText: {
    color: '#7a4b1a',
    fontWeight: '800',
    fontSize: 15,
  },
  dangerButton: {
    backgroundColor: '#a33821',
    borderRadius: 999,
    paddingHorizontal: 18,
    paddingVertical: 12,
  },
  dangerButtonText: {
    color: '#fff7ea',
    fontWeight: '800',
    fontSize: 15,
  },
  dangerCard: {
    borderRadius: 20,
    padding: 16,
    borderWidth: 1,
    gap: 10,
  },
  dangerCardTitle: {
    fontSize: 16,
    lineHeight: 20,
    fontWeight: '800',
  },
  dangerCardBody: {
    fontSize: 14,
    lineHeight: 21,
  },
  settingsGearButton: {
    width: 38,
    height: 38,
    borderRadius: 999,
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  settingsGearIcon: {
    fontSize: 18,
    fontWeight: '800',
  },
  settingsOverlay: {
    position: 'absolute',
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    alignItems: 'center',
    justifyContent: 'center',
    padding: 20,
    zIndex: 1000,
    elevation: 1000,
  },
  settingsBackdrop: {
    position: 'absolute',
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    backgroundColor: 'rgba(18, 15, 12, 0.48)',
  },
  settingsSheet: {
    width: '100%',
    maxWidth: 420,
    maxHeight: '88%',
    borderRadius: 28,
    borderWidth: 1,
    padding: 24,
  },
  settingsScroll: {
    width: '100%',
  },
  settingsScrollContent: {
    gap: 16,
    paddingBottom: 4,
    paddingHorizontal: 32,
  },
  timerSheet: {
    maxWidth: 460,
    padding: 20,
    gap: 12,
    margin: 16,
  },
  referenceSheet: {
    maxWidth: 560,
  },
  timerModalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  timerCloseButton: {
    width: 32,
    height: 32,
    borderRadius: 999,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
  },
  timerCloseText: {
    fontSize: 18,
    fontWeight: '700',
    lineHeight: 20,
  },
  settingsEyebrow: {
    fontSize: 12,
    letterSpacing: 1.2,
    textTransform: 'uppercase',
    fontWeight: '700',
  },
  settingsTitle: {
    fontSize: 28,
    lineHeight: 32,
    fontWeight: '800',
  },
  settingsBody: {
    fontSize: 15,
    lineHeight: 22,
  },
  settingsSection: {
    borderRadius: 20,
    borderWidth: 1,
    padding: 16,
    gap: 14,
  },
  settingsSectionTitle: {
    fontSize: 16,
    fontWeight: '800',
  },
  settingsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 16,
  },
  settingsCopy: {
    flex: 1,
    gap: 4,
  },
  settingsLabel: {
    fontSize: 16,
    fontWeight: '700',
  },
  settingsHint: {
    fontSize: 14,
    lineHeight: 20,
  },
  timerCountInputError: {
    borderWidth: 2,
  },
  timerCountErrorText: {
    fontSize: 13,
    lineHeight: 18,
    fontWeight: '700',
    marginTop: -6,
  },
  settingsCloseButton: {
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 999,
    paddingVertical: 14,
    paddingHorizontal: 20,
  },
  settingsCloseText: {
    fontSize: 15,
    fontWeight: '800',
  },
  directionHighlight: {
    borderRadius: 6,
    paddingHorizontal: 2,
  },
  editedDirectionCard: {
    borderWidth: 2,
    borderColor: '#d1a65c',
  },
  directionStepHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 12,
  },
  directionStepMeta: {
    flex: 1,
    gap: 4,
  },
  directionStepNumber: {
    fontSize: 16,
    lineHeight: 20,
    fontWeight: '800',
  },
  directionAnnotationStack: {
    gap: 10,
  },
  directionAnnotationCard: {
    borderRadius: 16,
    borderWidth: 1,
    paddingHorizontal: 14,
    paddingVertical: 12,
    gap: 6,
  },
  directionAnnotationLabel: {
    fontSize: 12,
    textTransform: 'uppercase',
    letterSpacing: 1,
    fontWeight: '800',
  },
  directionAnnotationText: {
    fontSize: 14,
    lineHeight: 21,
  },
  timerStack: {
    gap: 12,
    paddingHorizontal: 12,
  },
  timerHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  timerRemainingText: {
    fontSize: 14,
    fontWeight: '800',
  },
  timerDurationInput: {
    maxWidth: 160,
  },
  timerTrack: {
    height: 10,
    borderRadius: 999,
    overflow: 'hidden',
  },
  timerFill: {
    height: '100%',
    borderRadius: 999,
  },
});
